[tool.poetry]
name = "medical-chatbot"
version = "0.1.0"
description = ""
authors = ["Sadman Sakib <sadmansakib25091570@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pandas = "2.2.2"
langchain = "0.0.28"
transformers = "4.35.0"
openai = "0.28.0"
joblib = "1.3.2"
tiktoken = "0.4.0"
seaborn = "0.12.2"
jupyterlab = "4.2.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
